version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: leads_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - leads_net

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: leads_server
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/leads_db?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    depends_on:
      - mongo
    networks:
      - leads_net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: leads_client
    restart: unless-stopped
    ports:
      - '3000:80'
    depends_on:
      - server
    networks:
      - leads_net

volumes:
  mongo_data:

networks:
  leads_net:
    driver: bridge
